version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18.x

  build:
    commands:
      - echo install process started
      - npm install node-sass@
      - npm install 
      - npm install -g @angular/cli    
      - ng build
      - echo build process finished, we should uplload to S3 now
      - cd dist/
      - ls -la
      - aws s3 sync . s3://angular-mukul-demo --delete
